services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: trx
      POSTGRES_USER: trx
      POSTGRES_PASSWORD: password
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trx -d trx"]
      interval: 10s
      timeout: 5s
      retries: 5

  trx:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      # DATABASE_TYPE: SQLITE
      # DATABASE_CONNECTION_STRING: /workspace/sample.db
      DATABASE_TYPE: POSTGRESQL
      DATABASE_CONNECTION_STRING: host=postgres port=5432 dbname=trx user=trx password=password
      # DATABASE_TYPE: ODBC
      # DATABASE_CONNECTION_STRING: DRIVER={PostgreSQL Unicode};SERVER=postgres;PORT=5432;DATABASE=trx;UID=trx;PWD=password;
    volumes:
      - ./examples:/workspace/
    command: ["serve"]