global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'trx-monitor'

scrape_configs:
- job_name: 'trx-server'
  scrape_interval: 5s
  static_configs:
  - targets: [ 'trx:8080' ]
    labels:
      service: 'trx'
      environment: 'development'
